name: Build
on:
  workflow_dispatch:
  push:
    paths-ignore:
    - '*.md'
    - 'docs/**'
    branches:
    - 'master'
    tags-ignore:
    - '**'
  pull_request:
    paths-ignore:
    - '*.md'
    - 'docs/**'
env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
defaults:
  run:
    shell: pwsh
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v1
    - name: Set up .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore
      run: .\build.ps1 restore
    - name: Build
      run: .\build.ps1 build --skip restore
